"""Create a baseline migrations

Revision ID: 1b69d27ea00a
Revises: 95e813f9e700
Create Date: 2025-05-05 12:12:09.633521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b69d27ea00a'
down_revision: Union[str, None] = '95e813f9e700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('deadline', sa.DATE(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'cancel', 'completed', name='statustype'), server_default='pending', nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('Asia/Tashkent', NOW())"), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('Asia/Tashkent', NOW())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('Asia/Tashkent', NOW())"), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text("TIMEZONE('Asia/Tashkent', NOW())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('todos')
    # ### end Alembic commands ###
